# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    env:
      GIST_ID: d5057d855994a2ab855fe47788858e52

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 14.x, 12.x ]

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKERHUB_USER: ${{secrets.DOCKERHUB_USER}}
        DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
        TAG: ${{steps.set_var.outputs.TAG}}
      run: |
        echo $TAG
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - run: npm run typedoc
    - run: npm run eslint

    # Only run the coverage once
    - if: ${{ matrix.node-version == '16.x' }}
      name: Get Coverage for badge
      run: |
        # var SUMMARY = [
        #   '',
        #   '=============================== Coverage summary ===============================',
        #   'Statements   : 32.5% ( 39/120 )',
        #   'Branches     : 38.89% ( 21/54 )',
        #   'Functions    : 21.74% ( 5/23 )',
        #   'Lines        : 31.93% ( 38/119 )',
        #   '================================================================================',
        #   ''
        # ];
        # SUMMARY = SUMMARY.split('\n')[5]; // 'Lines        : 31.93% ( 38/119 )'
        # SUMMARY = SUMMARY.split(':')[1].split('(')[0].trim(); // '31.93%'
        SUMMARY="$(npm test -- --coverageReporters='text-summary' | tail -2 | head -1)"
        TOKENS=($SUMMARY)
        # process.env.COVERAGE = '31.93%';
        echo "COVERAGE=$(echo ${TOKENS[2]})" >> $GITHUB_ENV

        # var REF = 'refs/pull/27/merge.json';
        REF=${{ github.ref }}
        # console.log('github.ref: ' + REF);
        echo "github.ref: $REF"
        # var PATHS = REF.split('/');
        IFS='/' read -ra PATHS <<< "$REF"
        # var BRANCH_NAME = PATHS[1] + PATHS[2];
        BRANCH_NAME="${PATHS[1]}_${PATHS[2]}"
        # console.log(BRANCH_NAME); // 'pull_27'
        echo $BRANCH_NAME
        # process.env.BRANCH = 'pull_27';
        echo "BRANCH=$(echo ${BRANCH_NAME})" >> $GITHUB_ENV
    - if: ${{ matrix.node-version == '16.x' }}
      name: Create the Badge
      uses: schneegans/dynamic-badges-action@v1.0.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: ${{ env.GIST_ID }}
        filename: typescript-template__${{ env.BRANCH }}.json
        label: Test Coverage
        message: ${{ env.COVERAGE }}
        color: green
        namedLogo: jest
    - if: ${{ github.ref != 'refs/heads/main' && matrix.node-version == '16.x' && matrix.os == 'ubuntu-latest' }}
      uses: romeovs/lcov-reporter-action@v0.2.16
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        lcov-file: ./coverage/lcov.info
    - if: ${{ github.ref != 'refs/heads/main' && matrix.node-version == '16.x' && matrix.os == 'ubuntu-latest' }}
      name: Update the Badge URL in the pull request body
      run: |
        BODY=$(curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/{{ github.repository }}/pulls/${{ github.event.pull_request.number }} | jq .body | sed -En "s/protocol__pull_##.json/protocol__pull_${{ github.event.pull_request.number }}.json/p")
        JSON="{\"body\":$(echo $BODY | jq -sR .)}"
        curl \
          -X POST \
          -H "Authorization: token ${{ secrets.GIST_SECRET }}" \
          -H "Content-Type: application/json" \
          -d $JSON \
          https://api.github.com/repos/{{ github.repository }}/pulls/${{ github.event.pull_request.number }}
    - if: ${{ matrix.node-version == '16.x' }}
      uses: EndBug/add-and-commit@v7
      with:
        add: 'src/**'
        message: 'ESLint on src/'
    - if: ${{ matrix.node-version == '16.x' }}
      uses: EndBug/add-and-commit@v7
      with:
        add: 'test/**'
        message: 'ESLint on test/'
    - if: ${{ github.ref == 'refs/heads/main' && matrix.node-version == '16.x' }}
      uses: EndBug/add-and-commit@v7
      with:
        add: 'docs/api/**'
        message: 'Updating documentation'
    - if: ${{ github.ref == 'refs/heads/main' && matrix.node-version == '16.x' }}
      name: Deploy documentation
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./api/docs
    - if: ${{ github.ref == 'refs/heads/main' && matrix.node-version == '16.x' }}
      name:  'Automated Version Bump'
      uses:  'phips28/gh-action-bump-version@master'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        default: prerelease
        commit-message: 'CI: bumps version to {{version}} [skip ci]'
    - if: ${{ github.ref == 'refs/heads/main' && matrix.node-version == '16.x' }}
      name: Publish to npm
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
    - id: set_var
      run: |
        content=`cat package.json`
        # the following lines are only required for multi line json
        content="${content//'%'/'%25'}"
        content="${content//$'\n'/'%0A'}"
        content="${content//$'\r'/'%0D'}"
        # end of optional handling for multi line json
        echo "::set-output name=packageJson::$content"
    - run: |
        echo Publish to docker $TAG
    - if: ${{ github.ref == 'refs/heads/main' && matrix.node-version == '16.x' }}
      name: docker login
      env:
        DOCKERHUB_USER: ${{secrets.DOCKERHUB_USER}}
        DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
      run: |
        TAG="${{fromJson(steps.set_var.outputs.packageJson).version}}"
        echo Publish to docker latest and $TAG
        docker login -u $DOCKERHUB_USER -p $DOCKERHUB_TOKEN
        docker build . --file Dockerfile --tag yoannd/bebar:$TAG
        docker build . --file Dockerfile --tag yoannd/bebar:latest
        docker push yoannd/bebar:$TAG
        docker push yoannd/bebar:latest
